// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCyZR8Ul3j07Ya0apvBw82_aWju7VDPpw',
    appId: '1:860313193173:web:2c6d76d2c290aa1321f05c',
    messagingSenderId: '860313193173',
    projectId: 'pak-cafe-3ac09',
    authDomain: 'pak-cafe-3ac09.firebaseapp.com',
    databaseURL: 'https://pak-cafe-3ac09-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pak-cafe-3ac09.appspot.com',
    measurementId: 'G-TRKCTRPSZF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuVcPVfndCk880hMl6JB0ASsmsuE1yyW0',
    appId: '1:860313193173:android:511533355e0d9dc321f05c',
    messagingSenderId: '860313193173',
    projectId: 'pak-cafe-3ac09',
    databaseURL: 'https://pak-cafe-3ac09-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pak-cafe-3ac09.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgHFShPqoqKIkI1Y05aQlsk_j6IzXMLdo',
    appId: '1:860313193173:ios:7d8a6008ff06ac8321f05c',
    messagingSenderId: '860313193173',
    projectId: 'pak-cafe-3ac09',
    databaseURL: 'https://pak-cafe-3ac09-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pak-cafe-3ac09.appspot.com',
    iosClientId: '860313193173-50k4pmgkq6po88ru23lmq2t1saiph6hq.apps.googleusercontent.com',
    iosBundleId: 'com.example.pakAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgHFShPqoqKIkI1Y05aQlsk_j6IzXMLdo',
    appId: '1:860313193173:ios:7d8a6008ff06ac8321f05c',
    messagingSenderId: '860313193173',
    projectId: 'pak-cafe-3ac09',
    databaseURL: 'https://pak-cafe-3ac09-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pak-cafe-3ac09.appspot.com',
    iosClientId: '860313193173-50k4pmgkq6po88ru23lmq2t1saiph6hq.apps.googleusercontent.com',
    iosBundleId: 'com.example.pakAdmin',
  );
}
